### ISSUE TITLE
Discovered something interesting

### ISSUE THREAD

**Issue by mabdullahabid** [artxia/Action-NotionSite#1]
If you're using your main GitHub repo, e.g. example.github.io for this project with a CNAME setup for a custom domain then you don't need to do the CloudFlare worker proxy re-route. You can just set name = "." and it will deploy the code to the root directory which is then available directly at your root domain example.github.io (example.com with CNAME setup). Pretty neat!

**Comment by artxia** [comment]
The domain name set by “GitHub Pages Custom domain” can only be accessed using `yourdomain.com/blog`, and the domain name set by Cloudflare can be accessed using `yourdomain.com` without the file address behind.

**Comment by mabdullahabid** [comment]
That's not entirely correct. I named my repository `mabdullahabid.github.io` instead of blog so it's available at the root domain instead of `/blog`. Then I used a custom domain without CloudFlare workers to just display traffic at `mabdullahabid.com`.

**Comment by artxia** [comment]
Yes I know, I think this setting is the default GitHub setting and should be known to everyone. That's why it's not written in the README

**Comment by mabdullahabid** [comment]
Ah okay. Thanks for this. I thought we had to use the worker in order to get the blog at the root domain. Anyways, this is an amazing project. Thanks for this!

Btw, were you able to solve the Safari design issues?

**Comment by artxia** [comment]
Thanks for the reminder, I will write the hint that the default use of GitHub Pages dedicated projects can be simply configured with a domain name to the README.
The Safari display issue needs to be fixed by the core project author. I can't do anything about it.
