### ISSUE TITLE
使用了你的 template，但是 GitHub action 跑了2个多小时还没跑完。是什么原因

### ISSUE THREAD

**Issue by Mvbbb** [artxia/Action-NotionSite#3]
![image](https://user-images.githubusercontent.com/56795364/114269558-749a9300-9a3a-11eb-87ba-9af6ecd04aa4.png)
![image](https://user-images.githubusercontent.com/56795364/114269596-998f0600-9a3a-11eb-8003-f24407078375.png)

**Comment by artxia** [comment]
是不是你的文档内容太多路径也多？这种情况，只能等待第一次运行结果看看。。
可以试试删除`> test.log 2>&1`以显示更多日志。（为了隐私，调试完成后建议加回去）
 
另外如果是因为文档内容庞大导致，为了方便以后运行&提交，建议将`SINGLE_COMMIT: true`改为`false`, 以减小pull量

**Comment by Mvbbb** [comment]
> 是不是你的文档内容太多路径也多？这种情况，只能等待第一次运行结果看看。。
> 可以试试删除`> test.log 2>&1`以显示更多日志。（为了隐私，调试完成后建议加回去）
> 
> 另外如果是因为文档内容庞大导致，为了方便以后运行&提交，建议将`SINGLE_COMMIT: true`改为`false`, 以减小pull量

应该是我文章太多了的缘故
