### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by philfreo** [artxia/Action-NotionSite#4]
I just tried this. I setup a "Repository Secret" with just a `name` & `page` (notion URL)

When triggering the workflow it fails on the `loconotion` step...

<img width="647" alt="Screen Shot 2022-11-02 at 9 55 45 PM" src="https://user-images.githubusercontent.com/97612/199634455-5b851619-6019-4db3-a7a9-1c67fca72728.png">

**Comment by artxia** [comment]
Already fixed
